# Generated by Django 5.1.4 on 2025-02-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
