# Generated by Django 5.1.4 on 2025-02-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_rename_userdata_universal_alter_universal_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshots',
            old_name='user_id',
            new_name='user',
        ),
    ]
