# Generated by Django 5.1.4 on 2025-01-17 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_userdata_subject_matters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='general_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
